#include "buzzer_song.h"

const MUSIC_NOTE START_UP[] = {{NOTE_G,6},{NOTE_B,6},{NOTE_D,7},{NOTE_G,7},{NOTE_G,7},{NOTE_END}};
const MUSIC_NOTE START_UP2[] = {{NOTE_B,6},{NOTE_D,7},{NOTE_G,7},{NOTE_B,7},{NOTE_B,7},{NOTE_END}};
const MUSIC_NOTE SUCCESSFUL_SOUND[] = {{NOTE_C,7}, {NOTE_D,7}, {NOTE_E,7}, {NOTE_END}};
const MUSIC_NOTE FAIL_SOUND[] = {{NOTE_C, 4}, {NOTE_C, 4}, {NOTE_END}};
const MUSIC_NOTE CLICK[] = {{NOTE_G, 7}, {NOTE_END}};

const MUSIC_NOTE MARIO_BEGIN[] = {
   {NOTE_E, 7}, {NOTE_REST}, {NOTE_E, 7}, {NOTE_E, 7}, {NOTE_REST}, {NOTE_REST}, {NOTE_E, 7}, {NOTE_E, 7},
  {NOTE_REST},{NOTE_REST},{NOTE_C, 7},{NOTE_C, 7},{NOTE_E, 7},{NOTE_E, 7},{NOTE_REST},{NOTE_REST},
   {NOTE_G, 7}, {NOTE_G, 7},{NOTE_REST},{NOTE_REST},{NOTE_REST},{NOTE_REST},{NOTE_REST},{NOTE_REST},
  {NOTE_G, 6}, {NOTE_G, 6},{NOTE_G, 6},{NOTE_END}
};

const MUSIC_NOTE MARIO[] = {
  {NOTE_C, 7}, {NOTE_REST}, {NOTE_REST}, {NOTE_G, 6}, {NOTE_REST}, {NOTE_REST}, {NOTE_E, 6}, {NOTE_REST},
  {NOTE_REST}, {NOTE_A, 6}, {NOTE_REST}, {NOTE_B, 6}, {NOTE_REST}, {NOTE_Bb, 6},{NOTE_A, 6}, {NOTE_REST},
  {NOTE_G, 6}, {NOTE_REST}, {NOTE_E, 7}, {NOTE_G, 7}, {NOTE_A, 7}, {NOTE_REST}, {NOTE_F, 7}, {NOTE_G, 7},
  {NOTE_REST}, {NOTE_E, 7}, {NOTE_REST}, {NOTE_C, 7}, {NOTE_D, 7}, {NOTE_B, 6}, {NOTE_REST}, {NOTE_REST},
    
  {NOTE_C, 7}, {NOTE_REST}, {NOTE_REST}, {NOTE_G, 6}, {NOTE_REST}, {NOTE_REST}, {NOTE_E, 6}, {NOTE_REST},
  {NOTE_REST}, {NOTE_A, 6}, {NOTE_REST}, {NOTE_B, 6}, {NOTE_REST}, {NOTE_Bb, 6},{NOTE_A, 6}, {NOTE_REST},
  {NOTE_G, 6}, {NOTE_REST}, {NOTE_E, 7}, {NOTE_G, 7}, {NOTE_A, 7}, {NOTE_REST}, {NOTE_F, 7}, {NOTE_G, 7},
  {NOTE_REST}, {NOTE_E, 7}, {NOTE_REST}, {NOTE_C, 7}, {NOTE_D, 7}, {NOTE_B, 6}, {NOTE_REST}, {NOTE_REST},
  
  {NOTE_REST}, {NOTE_REST}, {NOTE_G, 7}, {NOTE_Gb, 7},{NOTE_F, 7}, {NOTE_Eb, 7},{NOTE_REST}, {NOTE_E, 7},
  {NOTE_REST}, {NOTE_Ab, 6},{NOTE_A, 6}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_A, 6}, {NOTE_C, 7}, {NOTE_D, 7},
  {NOTE_REST}, {NOTE_REST}, {NOTE_G, 7}, {NOTE_Gb, 7},{NOTE_F, 7}, {NOTE_Eb, 7},{NOTE_REST}, {NOTE_E, 7},
  {NOTE_REST}, {NOTE_C, 8}, {NOTE_REST}, {NOTE_C, 8}, {NOTE_C, 8}, {NOTE_REST}, {NOTE_G, 6}, {NOTE_REST},
  
  {NOTE_C, 6}, {NOTE_REST}, {NOTE_G, 7}, {NOTE_Gb, 7},{NOTE_F, 7}, {NOTE_Eb, 7},{NOTE_REST}, {NOTE_E, 7},
  {NOTE_REST}, {NOTE_Ab, 6},{NOTE_A, 6}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_A, 6}, {NOTE_C, 7}, {NOTE_D, 7},
  {NOTE_REST}, {NOTE_REST}, {NOTE_Eb, 7},{NOTE_REST},{NOTE_REST}, {NOTE_D, 7}, {NOTE_REST}, {NOTE_REST},
  {NOTE_C, 7}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST},
  
  
  {NOTE_END}
};

const MUSIC_NOTE MARIO2[] = {
  {NOTE_C, 7}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_C, 7}, {NOTE_D, 7}, {NOTE_REST},
  {NOTE_E, 7}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_A, 6}, {NOTE_G, 6}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST},
  {NOTE_C, 7}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_C, 7}, {NOTE_D, 7}, {NOTE_REST},
  {NOTE_E, 7}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST},
	
  {NOTE_C, 7}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_C, 7}, {NOTE_D, 7}, {NOTE_REST},
  {NOTE_E, 7}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_A, 6}, {NOTE_G, 6}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST},
  {NOTE_E, 7}, {NOTE_E, 7}, {NOTE_REST}, {NOTE_E, 7}, {NOTE_REST}, {NOTE_C, 7}, {NOTE_E, 7}, {NOTE_REST},
  {NOTE_G, 7}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST}, {NOTE_G, 6}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST},
	
	{NOTE_E, 7}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_G, 6}, {NOTE_REST}, {NOTE_REST}, {NOTE_Gs,6}, {NOTE_REST},
  {NOTE_A, 6}, {NOTE_F, 7}, {NOTE_REST}, {NOTE_F, 7}, {NOTE_A, 6}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST},
	{NOTE_B, 6}, {NOTE_A, 7}, {NOTE_REST}, {NOTE_A, 7}, {NOTE_A, 7}, {NOTE_G, 7}, {NOTE_REST}, {NOTE_F, 7},
  {NOTE_E, 7}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_A, 6}, {NOTE_G, 6}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST},

	{NOTE_E, 7}, {NOTE_C, 7}, {NOTE_REST}, {NOTE_G, 6}, {NOTE_REST}, {NOTE_REST}, {NOTE_Gs,6}, {NOTE_REST},
  {NOTE_A, 6}, {NOTE_F, 7}, {NOTE_REST}, {NOTE_F, 7}, {NOTE_A, 6}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST},
	{NOTE_B, 6}, {NOTE_F, 7}, {NOTE_REST}, {NOTE_F, 7}, {NOTE_F, 7}, {NOTE_E, 7}, {NOTE_REST}, {NOTE_D, 7},
  {NOTE_C, 7}, {NOTE_G, 6}, {NOTE_REST}, {NOTE_E, 6}, {NOTE_C, 6}, {NOTE_REST}, {NOTE_REST}, {NOTE_REST},
	
  {NOTE_END}
};
const MUSIC_NOTE MARIO_END[] = {
  {NOTE_B, 6}, {NOTE_B, 6}, {NOTE_F, 7}, {NOTE_F, 7}, {NOTE_REST}, {NOTE_REST}, {NOTE_F, 7}, {NOTE_REST},
  {NOTE_F, 7},{NOTE_F, 7},{NOTE_E, 7},{NOTE_E, 7},{NOTE_REST},{NOTE_REST},{NOTE_D, 7},{NOTE_D, 7},
  {NOTE_C, 7}, {NOTE_C, 7},{NOTE_G, 6},{NOTE_G, 6},{NOTE_REST},{NOTE_REST},{NOTE_E, 6},{NOTE_E, 6},
  {NOTE_C, 6}, {NOTE_C, 6},{NOTE_END}
};

const MUSIC_NOTE BIRTHDAY_SONG[] = {
	{NOTE_D,6},{NOTE_REST},{NOTE_D,6},
	{NOTE_E,6},{NOTE_E,6},{NOTE_E,6},
	{NOTE_D,6},{NOTE_D,6},{NOTE_D,6},
	{NOTE_G,6},{NOTE_G,6},{NOTE_G,6},
	{NOTE_Fs,6},{NOTE_Fs,6},{NOTE_Fs,6},
	{NOTE_Fs,6},{NOTE_Fs,6},{NOTE_REST},
	
	{NOTE_D,6},{NOTE_REST},{NOTE_D,6},
	{NOTE_E,6},{NOTE_E,6},{NOTE_E,6},
	{NOTE_D,6},{NOTE_D,6},{NOTE_D,6},
	{NOTE_A,6},{NOTE_A,6},{NOTE_A,6},
	{NOTE_G,6},{NOTE_G,6},{NOTE_G,6},
	{NOTE_G,6},{NOTE_G,6},{NOTE_REST},
	
	{NOTE_D,6},{NOTE_REST},{NOTE_D,6},
	{NOTE_D,7},{NOTE_D,7},{NOTE_D,7},	
	{NOTE_B,6},{NOTE_B,6},{NOTE_B,6},	
	{NOTE_G,6},{NOTE_G,6},{NOTE_G,6},	
	{NOTE_Fs,6},{NOTE_Fs,6},{NOTE_Fs,6},
	{NOTE_E,6},{NOTE_E,6},{NOTE_E,6},
	
	{NOTE_C,7},{NOTE_REST},{NOTE_C,7},
	{NOTE_B,6},{NOTE_B,6},{NOTE_B,6},	
	{NOTE_G,6},{NOTE_G,6},{NOTE_G,6},	
	{NOTE_A,6},{NOTE_A,6},{NOTE_A,6},	
	{NOTE_G,6},{NOTE_G,6},{NOTE_G,6},	
	{NOTE_G,6},{NOTE_G,6},{NOTE_END}
};
